## 4ndr0hack.bash

# Shell variables
# Generated by 'wal'
wallpaper="/home/andro/Wallpapers/4ndr0arch.png"
# Special
background='#01161b'
foreground='#66FFFF'
cursor='#79deea'
# Colors

color0='#01161b'
color1='#007b82'
color2='#028c94'
color3='#039ca4'
color4='#04acb5'
color5='#05bbc5'
color6='#06ccd7'
color7='#a3b5b8'
color8='#01161b'
color9='#007b82'
color10='#028c94'
color11='#039ca4'
color12='#04acb5'
color13='#05bbc5'
color14='#06ccd7'
color15='#a3b5b8'


# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"



