# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/126wall.jpg'

# Special
background='#111016'
foreground='#ef9999'
cursor='#ef9999'

# Colors
color0='#111016'
color1='#6B494C'
color2='#605F67'
color3='#923D3D'
color4='#8D494A'
color5='#A75253'
color6='#D55252'
color7='#ef9999'
color8='#a76b6b'
color9='#6B494C'
color10='#605F67'
color11='#923D3D'
color12='#8D494A'
color13='#A75253'
color14='#D55252'
color15='#ef9999'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
