# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/arch-linux-wallpaper-b9c0f8cd618acdfb4677881fe0f1566d.jpg'

# Special
background='#030303'
foreground='#dfdfdf'
cursor='#dfdfdf'

# Colors
color0='#030303'
color1='#212121'
color2='#252525'
color3='#2B2B2B'
color4='#343434'
color5='#575757'
color6='#9E9E9E'
color7='#dfdfdf'
color8='#9c9c9c'
color9='#212121'
color10='#252525'
color11='#2B2B2B'
color12='#343434'
color13='#575757'
color14='#9E9E9E'
color15='#dfdfdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
