# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/linux-arch-logo-technology-wallpaper-29b0b8ade1fa4d8b062798ef00f1c65d.jpg'

# Special
background='#0C1012'
foreground='#79deea'
cursor='#79deea'

# Colors
color0='#0C1012'
color1='#04778B'
color2='#048B92'
color3='#0395AB'
color4='#05A6B3'
color5='#04B1CB'
color6='#03ACDC'
color7='#79deea'
color8='#549ba3'
color9='#04778B'
color10='#048B92'
color11='#0395AB'
color12='#05A6B3'
color13='#04B1CB'
color14='#03ACDC'
color15='#79deea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
