# Author: 4ndr0666
# ===================================== // ALACRITTY.TOML //

## Imports and Startup

general.import = ["~/.config/wayfire/alacritty/themes/aura.toml", "~/.config/wayfire/alacritty/fonts.toml"]
#terminal.shell = { program = "/bin/zsh", args = ["--login"] }
#general.working_directory = "/home/andro/"
general.live_config_reload = true
general.ipc_socket = true

## Environment Setup

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

## Windows Dimensions

[window]
position = "None"
dynamic_padding = true
decorations = "full"
opacity = 1.0
blur = true
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

[window.dimensions]
columns = 95
lines = 24

[window.padding]
x = 12
y = 12

## Scroll

[scrolling]
history = 10000
multiplier = 3

## Bell

#[bell]
#animation = "EaseOutExpo"
#duration = 10
#command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"] }

## Clipboard

[selection]
save_to_clipboard = true

## Mouse

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true

## Misc


[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
