# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/candy-02.jpg'

# Special
background='#0c0a1c'
foreground='#d098bd'
cursor='#d098bd'

# Colors
color0='#0c0a1c'
color1='#8F3B79'
color2='#AD4379'
color3='#D74A74'
color4='#763386'
color5='#973A91'
color6='#D03FA0'
color7='#d098bd'
color8='#916a84'
color9='#8F3B79'
color10='#AD4379'
color11='#D74A74'
color12='#763386'
color13='#973A91'
color14='#D03FA0'
color15='#d098bd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
