## Colors configuration
[colors.primary]
background = "#030303"
foreground = "#dfdfdf"

[colors.normal]
black   = "#030303"
red     = "#212121"
green   = "#252525"
yellow  = "#2B2B2B"
blue    = "#343434"
magenta = "#575757"
cyan    = "#9E9E9E"
white   = "#dfdfdf"

[colors.bright]
black   = "#9c9c9c"
red     = "#212121"
green   = "#252525"
yellow  = "#2B2B2B"
blue    = "#343434"
magenta = "#575757"
cyan    = "#9E9E9E"
white   = "#dfdfdf"
