## Colors configuration
[colors.primary]
background = "#0c0a1c"
foreground = "#d098bd"

[colors.normal]
black   = "#0c0a1c"
red     = "#8F3B79"
green   = "#AD4379"
yellow  = "#D74A74"
blue    = "#763386"
magenta = "#973A91"
cyan    = "#D03FA0"
white   = "#d098bd"

[colors.bright]
black   = "#916a84"
red     = "#8F3B79"
green   = "#AD4379"
yellow  = "#D74A74"
blue    = "#763386"
magenta = "#973A91"
cyan    = "#D03FA0"
white   = "#d098bd"
