# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/f1459256_1.jpg'

# Special
background='#030303'
foreground='#dcd9c7'
cursor='#dcd9c7'

# Colors
color0='#030303'
color1='#53BA58'
color2='#CBC862'
color3='#7550B8'
color4='#4EC7AE'
color5='#9D9D9D'
color6='#EBEF9B'
color7='#dcd9c7'
color8='#9a978b'
color9='#53BA58'
color10='#CBC862'
color11='#7550B8'
color12='#4EC7AE'
color13='#9D9D9D'
color14='#EBEF9B'
color15='#dcd9c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
