#!/usr/bin/env bash
# File: ~/.config/wayfire/scripts/bravebeta
# Minimal overhead version

/usr/bin/brave-beta --allowlisted-extension-id=clngdbkpkpeebahjckkjfobafhncgmne \
	--enable-features=UsesOzonePlatform,AllowLegacyMV2Extensions,BraveGoogleSignInPermission,ExtensionManifestV2,FluentOverlayScrollbar,IsolatedWebApps,ToastRefinements,WaylandPerSurfaceScale,WaylandTextInputV3,WaylandUiScale \ 
	--disable-software-rasterizer --disable-crash-reporter=,brave,brave-beta --disable-accelerated-video-decode --disable-gpu-compositing --js-flags=--disable-optimizing-compilers --num-raster-threads=0 \
	--disable-background-networking --disable-component-extensions-with-background-pages & echo $! > /tmp/brave-beta.pid
