#!/usr/bin/env bash
# ~/.config/wayfire/scripts/bravebeta
# Optimized Brave Beta startup for Archcraft/Wayfire

BRAVE_BIN="/usr/bin/brave-beta"
PIDFILE="/tmp/brave-beta.pid"

"$BRAVE_BIN" \
  --allowlisted-extension-id=clngdbkpkpeebahjckkjfobafhncgmne \
  --disable-crash-reporter \
  --ozone-platform=wayland \
  --disk-cache-size=104857600 \
  "$@" &

echo $! > "$PIDFILE"
