#!/usr/bin/env bash

##
## Set GTK Themes, Icons, Cursor and Fonts

THEME='Sweet-v40'
ICONS='Colorful-Dark-Icons'
FONT='JetBrainsMono Nerd Font Regular 9'
CURSOR='Breeze-Adapta-Cursor'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
