#!/usr/bin/env bash

CONFIG="$HOME/.config/wayfire/waybar/config"
STYLE="$HOME/.config/wayfire/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --config ${CONFIG} --style ${STYLE}
fi
