#!/usr/bin/env bash
# Author: 4ndr0666

# ================= // WALLPAPER //
### Desc: Sets Wallpaper in Wayfire

## Dir
WALLPAPER='/home/andro/Wallpapers/Aura11920x1080.png'

## Swaybg
swaybg --output '*' --mode fill --image "$WALLPAPER"
