#!/usr/bin/env bash

# File: wallpaper
# Author: 4ndr0666
# Date: 10-20-24
## Sets Wallpaper in Wayfire

# ================================= // WALLPAPER //
WALLPAPER='/home/andro/Wallpapers/linux-arch-logo-technology-wallpaper-29b0b8ade1fa4d8b062798ef00f1c65d.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
